# 任务配置文件的名字可以当作优先级，例如：099会比100先执行，100会比101先执行

exp_name: 测试5
require:
  num_gpus: 3
  time_needed_to_start_completely: 60 # 执行任务的启动命令之后，需要多少秒才能占领GPU，防止GPU被错误判定为空闲状态
cmd: echo {exp_name} {gpus} {task_file_name} # {exp_name}， {gpus}， {task_file_name}会被替换成对应的值，如："测试5"、"0,1,2,"、"100.yaml"。如果不需要这些参数作为命令，则可以去掉
